### ISSUE TITLE
css

### ISSUE THREAD

**Issue by jilaokang** [jilaokang/PIKA#15]
## 动画

属性名：`@keyframes`

这个属性很厉害，用的好的人才是更厉害。

````css
@keyframes mymove {
  from {top:0px;}
  to {top:200px;}
}
````

**Comment by jilaokang** [comment]
## Sass

sass优雅的写法将css发挥到了极致

## 属性嵌套

**一个迷人的高可读性的写法**

````css
// 官网
.root{
  font:20px{
      weight:800;
  }
}

// 推荐
font:{
  size:20px;
  wight:800;
}
````

编译后

````css
.root{
  font:20px;
  font-weight:800;
}

**Comment by jilaokang** [comment]
## SCSS命名规范

scss命名规范为.元素-元素__属性

可以借助[sass-bem](https://github.com/zgabievi/sass-bem)实现

**Comment by jilaokang** [comment]
## sass-bem

- 全局导入sass-bem

````javascript
@import "node_modules/sass-bem/bem";
````

- 使用规范对照表
````sass
// .o-party
@include o("party") 

// .o-party-text
@include o("a"){
    @include p("text")
}

// .o-party-text__red
@include o("a"){
    @include p("text"){
        @include e("red")
    }
}
````

- 可以在设置里设置全局变量，如下，用法见[这里](https://github.com/mini-mpvue/mpvue-douban/blob/master/src/theme/var.scss)
````sass
$bem-component-namespace: 'md';
````
这样上面的所有的`o`就变成了`md`

**Comment by jilaokang** [comment]
## background-position:cover

图片是一个使用场景很多的元素，我们可以保证设计的图片符合尺寸，但各个手机不一样，尺寸差异，图片的兼容性尤为重要，这里针对background属性进行一个个人解读。

#### background-position

- 原尺寸：auto
- 自定义：50px 50px
- 天才：cover   

> 把背景图像扩展至足够大，以使背景图像完全覆盖背景区域。背景图像的某些部分也许无法显示在背景定位区域中。 --w3cschool

简而言之就是先让图片正常显示，然后对于多余的宽or高进行裁剪不显示。配合`background-position:center`咀嚼效果最佳。

**Comment by jilaokang** [comment]
## 过渡动画-webkit-transition: background-color 1s, transform 1s;

有时候真是想说外网强大，国内网站都搜不到这个属性的相关资料。

这个主要用于过渡动画
````scss
a {
    color: red;
    &:hover {
        -webkit-transition:color 1s;
    }
}
````

**多个属性的时候用`,`隔开**
